### ISSUE TITLE
Flickring on Chrome

### ISSUE THREAD

**Issue by Nishant-Rana** [matthieua/WOW#169]
Navigation on the top is flicker when is scroll the page after i scroll once the page on chrome , i am using bootstrap, parallax please look on this ulr and help me outoff this. Here is the url:http://www.onebcg.com

**Comment by attilaolah** [comment]
This is a known Crome issue.

An easy work-around is:

```css
nav {
  transform: translate3d(0, 0, 0);
}
```

(Any `transform` or `-webkit-transform` that ends with `3d` works).
